[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | .github/*
  | _scripts/*
  | venv/*
)/
| ^/atmocube/settings.py
| ^/manage.py
'''
[tool.isort]
line_length = 120
multi_line_output = 5