global:
  mlflow_uri: http://localhost:5000
predict:
  version: 2
train:
  experiment_name: my_experiment
  model_name: Regression
  count_vect_params:
    max_df: 0.7
    max_features: 1000
    min_df: 5
  catboost_params:
    depth: 8
    iterations: 100
    learning_rate: 0.1
    verbose: false
