global:
  mlflow_uri: http://localhost:5000
params:
  depth: 8
  iterations: 100
  learning_rate: 0.1
  max_df: 0.7
  max_features: 1000
  min_df: 5
  verbose: false
predict:
  version: 2
train:
  experiment_name: my_experiment
  model_name: Regression
